### ISSUE TITLE
大佬能否加个docker部署

### ISSUE THREAD

**Issue by Ham0mer** [androidmumo/bing-serve#1]
从php版本追过来的，用了好多年了，今天才发现更新了

**Comment by androidmumo** [comment]
可以，后续会考虑。

**Comment by androidmumo** [comment]
此仓库已合并入 https://github.com/androidmumo/bing ，后续将在新仓库维护。
关于支持docker部署的问题也已转移至新仓库，将在这个issues跟踪：https://github.com/androidmumo/bing/issues/3 。
上述事项计划在月底前完成。
