### ISSUE TITLE
运行后返回Cannot GET /

### ISSUE THREAD

**Issue by wujinpai** [androidmumo/bing-serve#2]
部署安装运行后访问返回Cannot GET /

**Comment by androidmumo** [comment]
尝试检查url是否配置正确。但是考虑到你的另外一条议题，我个人觉得有可能是你没有编译bing这个仓库，并将dist目录放到正确的位置。如果是直接访问API报错，那我仍然认为是url或者nginx(或者别的什么网页服务器)配置错误。
